import 'package:railway/models/seat.dart';

var seats = [
  Seat(seatNumber: 01, seatClass: 'Economy A'),
  Seat(seatNumber: 02, seatClass: 'Economy A'),
  Seat(seatNumber: 03, seatClass: 'Economy A'),
  Seat(seatNumber: 04, seatClass: 'Economy A'),
  Seat(seatNumber: 05, seatClass: 'Economy A'),
  Seat(seatNumber: 06, seatClass: 'Economy A'),
  Seat(seatNumber: 07, seatClass: 'Economy A'),
  Seat(seatNumber: 08, seatClass: 'Economy A'),
  Seat(seatNumber: 09, seatClass: 'Economy A'),
  Seat(seatNumber: 10, seatClass: 'Economy A'),
  Seat(seatNumber: 11, seatClass: 'Economy A'),
  Seat(seatNumber: 12, seatClass: 'Economy A'),
  Seat(seatNumber: 13, seatClass: 'Economy A'),
  Seat(seatNumber: 14, seatClass: 'Economy A'),
  Seat(seatNumber: 15, seatClass: 'Economy A'),
  Seat(seatNumber: 16, seatClass: 'Economy A'),
  Seat(seatNumber: 17, seatClass: 'Economy A'),
  Seat(seatNumber: 18, seatClass: 'Economy A'),
  Seat(seatNumber: 19, seatClass: 'Economy A'),
  Seat(seatNumber: 20, seatClass: 'Economy A'),
  Seat(seatNumber: 21, seatClass: 'Economy A'),
  Seat(seatNumber: 22, seatClass: 'Economy A'),
  Seat(seatNumber: 23, seatClass: 'Economy A'),
  Seat(seatNumber: 24, seatClass: 'Economy A'),
  Seat(seatNumber: 25, seatClass: 'Economy A'),
  Seat(seatNumber: 26, seatClass: 'Economy A'),
  Seat(seatNumber: 27, seatClass: 'Economy A'),
  Seat(seatNumber: 28, seatClass: 'Economy A'),
  Seat(seatNumber: 29, seatClass: 'Economy A'),
  Seat(seatNumber: 30, seatClass: 'Economy A'),
  Seat(seatNumber: 31, seatClass: 'Economy A'),
  Seat(seatNumber: 32, seatClass: 'Economy A'),
];
